name: CISA Scraping 🕷️

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at 00:00 UTC

  workflow_dispatch:

jobs:
  scrape_cisagov:
    name: CISA Scraping 🕷️
    runs-on: ubuntu-latest

    steps:
      - name: 🛠️ Check out repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Scrapy

      - name: 🕸️ Run Cisagov spider
        run: |
          cd spiders
          scrapy runspider cisagov.py -o out/cisagov.json

      - name: 📊 Compare & Upload agency data
        uses: ${{ github.repository }}/.github/workflows/compare_and_upload.yml@main
        with:
          agency_name: "CISA"
          agency_data_path: "out/cisagov.json"
