# ┌───────────── minute (0 - 59)
# │ ┌───────────── hour (0 - 23)
# │ │ ┌───────────── day of the month (1 - 31)
# │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
# │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
# │ │ │ │ │
# │ │ │ │ │
# │ │ │ │ │
# * * * * *

name: USA Scraping 🦅

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at 00:00 UTC
  workflow_dispatch:

jobs:
  scrape_usagov:
    name: Scrape USA.gov
    runs-on: ubuntu-latest

    steps:
      - name: 🛠️ Check out repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: 🏛️ Run Usagov script
        run: |
          cd spiders
          python usagov.py

      - name: 📊 Compare & Upload agency data
        uses: theboatymcboatface/allusgov/.github/workflows/compare_and_upload.yml@main
        with:
          agency_name: "USA"
          agency_data_path: "out/usagov.json"
